name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.3

      - name: Install dependencies
        run: |
          poetry install

      - name: Code quality checks
        run: |
          isort --check-only .
          black --check .
          flake8
          mypy src/app.py

      - name: Test with pytest
        run: |
           python -m pytest
